version: '3.8'

services:
  web:
    build: .
    container_name: tree_hole
    ports:
      - "5050:5050"  # 将主机5050端口映射到容器5050端口
    restart: unless-stopped  # 容器崩溃时自动重启
    environment:
      - FLASK_ENV=production  # 设置Flask环境变量（可选）
